
require "user.colorscheme"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.autotag"
require "user.nvim-ts-rainbow"
require "user.devicons"
require "user.colorizer"
require "user.symbol_outline"
require "user.hover"
require "user.lsp"
require "user.illuminate"
require "user.code_action_utils"
require "user.distand"
require "user.prettier"
require "user.navic"
require "user.smooth_cursor"
--[[ require "user.cinnamon" ]]
require "user.aerial"
require "user.competitest"

