require "core.options"
require("ui")
require "lsp"
require("themes")
require "user.keymaps"
require "user.plugins"
require "user.telescope"
require "user.treesitter"
require("editor")
require "user.comment"
require "user.gitsigns"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.autocommands"
require "user.symbol_outline"
require "user.hover"
require "user.illuminate"
require "user.code_action_utils"
require "user.prettier"
require "user.navic"
require "user.smooth_cursor"
--[[ require "user.cinnamon" ]]
require "user.aerial"
require "user.competitest"
