require "gungim.colorscheme"
require "gungim.options"
require("gungim.config"):load()
require "gungim.plugins"
require "gungim.cmp"
require "gungim.telescope"
require "gungim.autopairs"
require "gungim.comment"
require "gungim.gitsigns"
require "gungim.nvim_tree"
require "gungim.toggleterm".setup()
require "gungim.project"
require "gungim.impatient"
require("gungim.indentline").setup()
require "gungim.alpha"
require "gungim.whichkey"
require "gungim.autocommands"
require "gungim.autotag"
require "gungim.nvim_ts_rainbow"
require "gungim.devicons"
require "gungim.colorizer"
require "gungim.symbol_outline"
require "gungim.hover"
require "gungim.lsp"
require "gungim.illuminate"
require "gungim.code_action_utils"
require "gungim.prettier"
require "gungim.navic"
require "gungim.aerial"
require "gungim.competitest"
require "gungim.treesitter"
require("gungim.color_picker")
require("gungim.ui").setup()
